# Generated by Django 3.2.16 on 2022-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='output',
            field=models.FileField(null=True, upload_to='output/%Y/%m/%d'),
        ),
    ]
