# Generated by Django 3.2.16 on 2022-11-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='output',
        ),
        migrations.CreateModel(
            name='OutputDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.FileField(upload_to='output/%Y/%m/%d')),
                ('documents', models.ManyToManyField(to='myapp.Document')),
            ],
        ),
    ]
